### ISSUE TITLE
what's the command of generating the static site?

### ISSUE THREAD

**Issue by luckypoem** [TooTallNate/n8.io-old#12]
hi.

i cloned ur site,but what's the command of generating the static site?

as3:~/n8.io-site# ls
app.js    create-article.sh  Makefile      public     server.js
articles  lib                package.json  README.md  views
as3:~/n8.io-site#

**Comment by TooTallNate** [comment]
It's not a static site. It's dynamically created using the `libgit2` library, which is interacted with through the `node-ffi` module. To run the site, you simply need to run `node server.js`: https://github.com/TooTallNate/n8.io/blob/master/server.js

**Comment by luckypoem** [comment]
hi.

as3:~/n8.io-site# node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'ref'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/n8.io-site/app.js:6:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
as3:~/n8.io-site#

how to fix it?

**Comment by TooTallNate** [comment]
Run "npm install"

**Comment by luckypoem** [comment]
hi.
i ran "npm install" and "apt-get install libgit-ruby",but when i ran "node server.js",i still met error.why?
how to fix it?tks.

as3:~/n8.io-site# node server.js
/root/n8.io-site/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: libgit2.so: cannot open shared object file: No such file or directory
    at new DynamicLibrary (/root/n8.io-site/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/root/n8.io-site/node_modules/ffi/lib/library.js:45:12)
    at Object.<anonymous> (/root/n8.io-site/lib/git.js:59:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/n8.io-site/app.js:8:11)
as3:~/n8.io-site#

**Comment by TooTallNate** [comment]
Looks like you still don't have libgit2 installed. Try `apt-get install
libgit2-dev`

**Comment by luckypoem** [comment]
hi.
there is no libgit2-dev or libgit2 package in debian.i compiled libgit2 as per https://github.com/libgit2/libgit2:
as3:~# git clone -b master git://github.com/libgit2/libgit2.git
as3:~# mkdir libgit2/build
as3:~# cd libgit2/build
as3:~/libgit2/build# cmake .. -DBUILD_CLAR=OFF
as3:~/libgit2/build# cmake --build .
...
[ 96%] Building C object CMakeFiles/git2.dir/src/xdiff/xpatience.c.o
[ 97%] Building C object CMakeFiles/git2.dir/src/xdiff/xdiffi.c.o
[ 98%] Building C object CMakeFiles/git2.dir/src/unix/realpath.c.o
[ 99%] Building C object CMakeFiles/git2.dir/src/unix/map.c.o
[100%] Building C object CMakeFiles/git2.dir/deps/http-parser/http_parser.c.o
Linking C shared library libgit2.so
[100%] Built target git2
as3:~/libgit2/build# cd ~/n8.io-site
as3:~/n8.io-site# find / -name libgit2.so
/root/libgit2/build/libgit2.so
as3:~/n8.io-site# node server.js
/root/n8.io-site/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: libgit2.so: cannot open shared object file: No such file or directory
    at new DynamicLibrary (/root/n8.io-site/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/root/n8.io-site/node_modules/ffi/lib/library.js:45:12)
    at Object.<anonymous> (/root/n8.io-site/lib/git.js:59:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/n8.io-site/app.js:8:11)
as3:~/n8.io-site#

why i stii get the error: "Dynamic Linking Error: libgit2.so: cannot open shared object file: No such file or directory"? which dir should i copy /root/libgit2/build/libgit2.so to?
